sudo: required
language: bash
services:
  - docker
install: true

script:
  - docker build .
  - export DID=$(docker images -a | grep -m1 mageia-rpmbuilder | awk '{print $3}')
  - echo $DID
  - docker tag $DID jmiahman/mageia-rpmbuilder

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker jmiahman/mageia-rpmbuilder:latest;
    fi
