sudo: required
language: bash
services:
  - docker
install: true

script:
  - docker build .
  - export DID=$(docker images -a| awk '{print $3}' | grep ".[0-9].\|.[a-z]." -m1)
  - echo $DID
  - docker tag $DID jmiahman/mageia-rpmbuilder

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push jmiahman/mageia-rpmbuilder:latest;
    fi
